#environment configuration
churn_file: config/churn-test.yaml

#seed: 0

#process asynchrony
asynchrony:
  type: NoAsynchrony

#asynchrony:
#   type: UniformAsynchrony
#   uniform:
#     low: -0.1
#     high: 0.1

#time each method call takes. Ignored if NoAsynchrony
# op_duration: 100


network:
  type: ConstantNetwork
  latency: 10
  jitter:
    type: NoJitter
  loss: 0.0

#algorithm configuration
n: 10
fanout: 2
cycles: 10
period: 200
