latency_file: data/pl_226nodes.latencies

churn_file: config/churn-test.yaml

seed: 0

asynchrony: 
  type: NormalAsynchrony
  normal:
    mean: 0.0
    std_dev: 0.1

network: 
  type: ConstantNetwork
  latency: 100
  jitter:
    type: NoJitter
  loss: 0.0

op_duration: 200 

n: 10
fanout: 2
cycles: 2
period: 200
