churn_file: config/churn-test.yaml

seed: 0

network: 
  type: MatrixNetwork
  latency_file: "data/pl_226nodes.latencies"
  n: 10
  jitter: 
    type: NoJitter
  loss: 0.0

save: 300
save_filename: main_saved_state.bin
save_and_stop: true

op_duration: 200

n: 10
fanout: 2
cycles: 2
period: 200
