churn:
  - [0, join, 1]
  - [1000, join, 1.0]
  # - [2000, join, 1]
  # - [3000, join, 1]
  # - [4000, join, 1]
  # - [5000, join, 1]
  # - [6000, join, 1]
  # - [7000, join, 1]
  # - [8000, join, 1]
  # - [9000, join, 1]
  - [9999, leave, 2]
  - [10000, end]
