churn_file: config/conf-chord-succ_list.yaml

seed: 0

asynchrony: 
  type: NoAsynchrony

network: 
  type: ConstantNetwork
  latency: 10
  jitter:
    type: NoJitter
  loss: 0.0

op_duration: 100

# save: 10000
# save_filename: "chord-stable-1000_m32-end10000.bin"
# save_and_stop: true

n: 1000

m: 32 # identifier space from 0 to 2^m - 1
successor_list_size: 4

period_stabilize: 100
period_fix_fingers: 100
period_check_predecessor: 800
count: 0


churn:
  - [0, join, 1]
  - [1000, join, 1.0]
  - [10000, end]
