churn_file: config/churn-chord.yaml

seed: 0

asynchrony: 
  type: NoAsynchrony

network: 
  type: ConstantNetwork
  latency: 10
  jitter:
    type: NoJitter
  loss: 0.0

op_duration: 100

save: 100000
save_filename: "chord-n10000_m64-end100K.bin"
save_and_stop: true

n: 10000

m: 64 # identifier space from 0 to 2^m - 1
successor_list_size: 8

period_stabilize: 100
period_fix_fingers: 100
period_check_predecessor: 800
count: 0
